version: "3.8"
services:
  db:
    image: "postgres:latest"
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: localdb
    container_name: postgres_local
    shm_size: 1GB